import MathlibAnnex.Analysis.CStarAlgebra.Representation.Basic
import Mathlib.Topology.Algebra.Module.ClosedSubmodule

/-! Cyclic subspaces of Hilbert-space star representations. -/

set_option autoImplicit false

namespace MathlibAnnex.Analysis.CStarAlgebra

universe u v

variable {A : Type u} [Semiring A] [Algebra ℂ A] [Star A]
variable {H : Type v}
variable [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

namespace Representation

/-- Invariance under an operator's adjoint makes the orthogonal complement
invariant under the operator. -/
theorem map_mem_orthogonal_of_adjoint_mem (T : H →L[ℂ] H)
    (K : Submodule ℂ H)
    (hK : ∀ y : H, y ∈ K → ContinuousLinearMap.adjoint T y ∈ K)
    {x : H} (hx : x ∈ Kᗮ) : T x ∈ Kᗮ := by
  rw [Submodule.mem_orthogonal]
  intro y hy
  rw [← ContinuousLinearMap.adjoint_inner_left]
  exact Submodule.inner_right_of_mem_orthogonal (hK y hy) hx

/-- The linear source orbit map at a vector. -/
noncomputable def orbitLinearMap (pi : Representation A H) (eta : H) : A →ₗ[ℂ] H where
  toFun a := pi a eta
  map_add' a b := by simp
  map_smul' c a := by simp

/-- The norm-closed cyclic subspace generated by a vector. -/
noncomputable def cyclicSubspace (pi : Representation A H) (eta : H) : Submodule ℂ H :=
  (LinearMap.range (orbitLinearMap pi eta)).topologicalClosure

theorem isClosed_cyclicSubspace (pi : Representation A H) (eta : H) :
    IsClosed (cyclicSubspace pi eta : Set H) :=
  by simpa [cyclicSubspace] using
    Submodule.isClosed_topologicalClosure (LinearMap.range (orbitLinearMap pi eta))

theorem self_mem_cyclicSubspace (pi : Representation A H) (eta : H) :
    eta ∈ cyclicSubspace pi eta := by
  apply Submodule.le_topologicalClosure
  refine ⟨1, ?_⟩
  simp [orbitLinearMap]

/-- The cyclic subspace is invariant under every represented element. -/
theorem map_mem_cyclicSubspace (pi : Representation A H) (eta : H)
    (a : A) {x : H} (hx : x ∈ cyclicSubspace pi eta) :
    pi a x ∈ cyclicSubspace pi eta := by
  have hx' : x ∈ closure (Set.range (orbitLinearMap pi eta)) := by
    change x ∈ (cyclicSubspace pi eta : Set H) at hx
    rw [cyclicSubspace, Submodule.topologicalClosure_coe,
      LinearMap.coe_range] at hx
    exact hx
  have hout : pi a x ∈ closure (Set.range (orbitLinearMap pi eta)) := by
    apply map_mem_closure (pi a).continuous hx'
    intro y hy
    obtain ⟨b, rfl⟩ := hy
    refine ⟨a * b, ?_⟩
    simp [orbitLinearMap]
  change pi a x ∈ (cyclicSubspace pi eta : Set H)
  rw [cyclicSubspace, Submodule.topologicalClosure_coe,
    LinearMap.coe_range]
  exact hout

/-- The cyclic subspace is invariant under adjoints as well as operators. -/
theorem adjoint_mem_cyclicSubspace (pi : Representation A H) (eta : H)
    (a : A) {x : H} (hx : x ∈ cyclicSubspace pi eta) :
    ContinuousLinearMap.adjoint (pi a) x ∈ cyclicSubspace pi eta := by
  rw [← ContinuousLinearMap.star_eq_adjoint, ← map_star pi]
  exact map_mem_cyclicSubspace pi eta (star a) hx

/-- Every cyclic subspace is closed and reducing. -/
theorem reduces_cyclicSubspace (pi : Representation A H) (eta : H) :
    pi.Reduces (cyclicSubspace pi eta) := by
  refine ⟨isClosed_cyclicSubspace pi eta, ?_⟩
  intro a x hx
  exact ⟨map_mem_cyclicSubspace pi eta a hx,
    adjoint_mem_cyclicSubspace pi eta a hx⟩

/-- The orthogonal projection onto a reducing subspace commutes with the
representation. -/
theorem starProjection_commutes_of_reduces (pi : Representation A H)
    (K : Submodule ℂ H) [K.HasOrthogonalProjection] (hK : pi.Reduces K)
    (a : A) :
    K.starProjection * pi a = pi a * K.starProjection := by
  apply ContinuousLinearMap.ext
  intro x
  change K.starProjection (pi a x) = pi a (K.starProjection x)
  apply K.eq_starProjection_of_mem_orthogonal'
  · exact (hK.2 a (K.starProjection x) (K.starProjection_apply_mem x)).1
  · apply map_mem_orthogonal_of_adjoint_mem (pi a) K
      (fun y hy ↦ (hK.2 a y hy).2)
    exact K.sub_starProjection_mem_orthogonal x
  · simp

/-- A nonzero vector is cyclic in a nonzero irreducible representation. -/
theorem cyclicSubspace_eq_top_of_isIrreducible (pi : Representation A H)
    (hirr : pi.IsIrreducible) {eta : H} (heta : eta ≠ 0) :
    cyclicSubspace pi eta = ⊤ := by
  rcases hirr.2 (cyclicSubspace pi eta) (reduces_cyclicSubspace pi eta) with hbot | htop
  · exfalso
    apply heta
    have hmem := self_mem_cyclicSubspace pi eta
    rw [hbot, Submodule.mem_bot] at hmem
    exact hmem
  · exact htop

/-- Predicate saying that the norm-closed represented orbit is all of the
Hilbert space. -/
def IsCyclicVector (pi : Representation A H) (eta : H) : Prop :=
  cyclicSubspace pi eta = ⊤

theorem isCyclicVector_of_isIrreducible (pi : Representation A H)
    (hirr : pi.IsIrreducible) {eta : H} (heta : eta ≠ 0) :
    pi.IsCyclicVector eta :=
  cyclicSubspace_eq_top_of_isIrreducible pi hirr heta

end Representation

end MathlibAnnex.Analysis.CStarAlgebra
