import Mathlib.Analysis.CStarAlgebra.GelfandNaimarkSegal
import MathlibAnnex.Analysis.InnerProductSpace.Reduction

/-!
# Cyclic subspaces of star representations

The algebraic orbit is closed only after taking its topological closure.  The
resulting subspace reduces a unital star representation, its orthogonal
projection commutes with the representation, and irreducibility promotes a
nonzero cyclic subspace to the whole Hilbert space.
-/

set_option autoImplicit false

open scoped InnerProduct

namespace StarAlgHom

variable {A H : Type*}
variable [CStarAlgebra A]
variable [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The linear orbit map at a vector. -/
noncomputable def orbitMap (π : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (ξ : H) : A →ₗ[ℂ] H where
  toFun a := π a ξ
  map_add' a b := by simp
  map_smul' c a := by simp

/-- The closed cyclic subspace generated by a vector. -/
noncomputable def cyclicSubspace (π : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (ξ : H) : Submodule ℂ H :=
  (LinearMap.range (orbitMap π ξ)).topologicalClosure

@[simp]
theorem orbit_mem_cyclicSubspace (π : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (ξ : H) (a : A) :
    π a ξ ∈ cyclicSubspace π ξ :=
  (LinearMap.range (orbitMap π ξ)).le_topologicalClosure
    (LinearMap.mem_range_self (orbitMap π ξ) a)

theorem isClosed_cyclicSubspace (π : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (ξ : H) :
    IsClosed (cyclicSubspace π ξ : Set H) :=
  (LinearMap.range (orbitMap π ξ)).isClosed_topologicalClosure

/-- Reduction for every operator in a representation. -/
def IsReducing (π : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (K : Submodule ℂ H) : Prop :=
  ∀ a, K.Reduces (π a)

/-- Topological irreducibility: the only closed reducing subspaces are zero
and the full Hilbert space. -/
def IsIrreducible (π : A →⋆ₐ[ℂ] (H →L[ℂ] H)) : Prop :=
  ∀ K : Submodule ℂ H, IsClosed (K : Set H) → IsReducing π K → K = ⊥ ∨ K = ⊤

private theorem cyclicSubspace_invariant (π : A →⋆ₐ[ℂ] (H →L[ℂ] H))
    (ξ : H) (b : A) : (cyclicSubspace π ξ).IsInvariantUnder (π b) := by
  intro x hx
  change x ∈ closure (LinearMap.range (orbitMap π ξ)) at hx
  change π b x ∈ closure (LinearMap.range (orbitMap π ξ))
  apply (show Set.MapsTo (π b) (LinearMap.range (orbitMap π ξ))
      (LinearMap.range (orbitMap π ξ)) by
    rintro _ ⟨a, rfl⟩
    exact ⟨b * a, by simp [orbitMap]⟩).closure (π b).continuous hx

theorem cyclicSubspace_isReducing (π : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (ξ : H) :
    IsReducing π (cyclicSubspace π ξ) := by
  intro a
  refine ⟨cyclicSubspace_invariant π ξ a, ?_⟩
  have hadj : π (star a) = ContinuousLinearMap.adjoint (π a) := by
    rw [map_star, ContinuousLinearMap.star_eq_adjoint]
  rw [← hadj]
  exact cyclicSubspace_invariant π ξ (star a)

theorem cyclicSubspace_eq_top (π : A →⋆ₐ[ℂ] (H →L[ℂ] H))
    (hπ : IsIrreducible π) {ξ : H} (hξ : ξ ≠ 0) : cyclicSubspace π ξ = ⊤ := by
  rcases hπ (cyclicSubspace π ξ) (isClosed_cyclicSubspace π ξ)
    (cyclicSubspace_isReducing π ξ) with hbot | htop
  · exfalso
    have hmem : ξ ∈ cyclicSubspace π ξ := by
      simpa using orbit_mem_cyclicSubspace π ξ (1 : A)
    rw [hbot, Submodule.mem_bot] at hmem
    exact hξ hmem
  · exact htop

end StarAlgHom

namespace Submodule

variable {𝕜 H : Type*}
variable [RCLike 𝕜]
variable [NormedAddCommGroup H] [InnerProductSpace 𝕜 H] [CompleteSpace H]

private theorem Reduces.orthogonal_invariant {K : Submodule 𝕜 H}
    {T : H →L[𝕜] H} (h : K.Reduces T) : Kᗮ.IsInvariantUnder T := by
  intro x hx y hy
  rw [← ContinuousLinearMap.adjoint_inner_left]
  exact (K.mem_orthogonal x).1 hx _ (h.2 hy)

/-- The orthogonal projection onto a reducing subspace commutes with the
operator. -/
theorem Reduces.starProjection_commute {K : Submodule 𝕜 H}
    [K.HasOrthogonalProjection] {T : H →L[𝕜] H} (h : K.Reduces T) :
    K.starProjection.comp T = T.comp K.starProjection := by
  apply ContinuousLinearMap.ext
  intro x
  apply K.eq_starProjection_of_mem_orthogonal'
  · exact h.1 (K.starProjection_apply_mem x)
  · exact h.orthogonal_invariant (K.sub_starProjection_mem_orthogonal x)
  · simp

/-- For a projected closed subspace, reducing an operator is equivalent to
commuting with its orthogonal projection. -/
theorem reduces_iff_starProjection_commute {K : Submodule 𝕜 H}
    [K.HasOrthogonalProjection] {T : H →L[𝕜] H} :
    K.Reduces T ↔ K.starProjection.comp T = T.comp K.starProjection := by
  constructor
  · exact Reduces.starProjection_commute
  · intro hcomm
    have hcommAdj : K.starProjection.comp (T†) =
        (T†).comp K.starProjection := by
      have h := congrArg ContinuousLinearMap.adjoint hcomm
      simpa only [ContinuousLinearMap.adjoint_comp,
        K.starProjection_isSymmetric.clm_adjoint_eq] using h.symm
    constructor
    · intro x hx
      rw [← K.starProjection_eq_self_iff, ← ContinuousLinearMap.comp_apply,
        hcomm, ContinuousLinearMap.comp_apply,
        K.starProjection_eq_self_iff.mpr hx]
    · intro x hx
      rw [← K.starProjection_eq_self_iff, ← ContinuousLinearMap.comp_apply,
        hcommAdj, ContinuousLinearMap.comp_apply,
        K.starProjection_eq_self_iff.mpr hx]

end Submodule
